// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRNFmxQ_ELmV4EYxwNXlTkq5ZZt-QmIvU',
    appId: '1:585728837923:web:ced5f39a889ee2dcba6496',
    messagingSenderId: '585728837923',
    projectId: 'tugsuyoo',
    authDomain: 'tugsuyoo.firebaseapp.com',
    storageBucket: 'tugsuyoo.appspot.com',
    measurementId: 'G-T3T59GC94D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGJPIV1-fNiWp80k9R-pZdPEsX3KqQ1pM',
    appId: '1:585728837923:android:52e18d764ba172ffba6496',
    messagingSenderId: '585728837923',
    projectId: 'tugsuyoo',
    storageBucket: 'tugsuyoo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHJ7Oc6vRpUYVqMbDB-DFbZFXZqbrWZeo',
    appId: '1:585728837923:ios:6bc41120244479cdba6496',
    messagingSenderId: '585728837923',
    projectId: 'tugsuyoo',
    storageBucket: 'tugsuyoo.appspot.com',
    iosBundleId: 'com.example.tugsuyoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHJ7Oc6vRpUYVqMbDB-DFbZFXZqbrWZeo',
    appId: '1:585728837923:ios:c7c581f38fadcd34ba6496',
    messagingSenderId: '585728837923',
    projectId: 'tugsuyoo',
    storageBucket: 'tugsuyoo.appspot.com',
    iosBundleId: 'com.example.tugsuyoo.RunnerTests',
  );
}
