const Map<String, String> vi = {
  'hello': 'Сайнуу',
  'multipleLanguage': 'Хэл сонгох',
  'task': 'Даалгаврууд',
  'add': 'Нэмэх',
  'language': 'Хэл сонгох',
  'about': 'Миний талаар',
  'mongolian': 'Монгол',
  'english': 'Ангил',
  'live_tasks': 'Хийгдээгүй',
  'done_tasks': 'Хийгдсэн',
  'total_tasks': 'Нийт',
  'report': 'Тайлан',
  'efficiency': 'Үр дүн',
  'home': 'Нүүр',
  'deleted': 'Устгагдсан',
  'tasks': 'Төлөвлөгөө',
  'new_task': 'Шинэ төлөвлөгөө ',
  'done': 'Биеэлсэн',
  'add_to': 'Нэмэх',
  'add_new': 'Шинээр нэмэх',
  'completed': 'Дууссан',
  'add_todos': 'Thêm mục tiêu',
  'add_todos_successfully': 'Амжилттай төрөл үүсэв',
  'please_enter_your_todo_item': 'Хамааралтай төрөлийг сонго уу',
  'please_enter_title': 'Сэдэвээ оруулна уу',
  'task_created': 'Төлөвлөгөө үүсгэх',
  'add_alram': 'Сэрүүлэг нэмэх',
  'never': 'Үргэлж',
  'everyday': 'Өдөр бүр',
  'title': 'Гарчиг',
  'optional': 'Không bắt buộc',
  'repeat': 'Буулгах',
  'monday': 'Даваа',
  'tuesday': 'Мягмар',
  'wednesday': 'Лхавга',
  'thursday': 'Пүрэв',
  'friday': 'Баасан',
  'saturday': 'Бямба',
  'sunday': 'Ням',
  'mon': 'Дав',
  'tue': 'Мяг',
  'wed': 'Лха',
  'thu': 'Пү',
  'fri': 'Баа',
  'sat': 'Бям',
  'sun': 'Ням',
  'alarm': 'Сэрүүлэг',
  'timer': 'Хугацаа хэмжигч',
  'clock': 'Цаг',
  'start': 'Эхлэх',
  'new_timer': 'Хугацаа',
  'pause': 'Зогсох',
  'resume': 'Үргэлжлүүлэх',
  'cancel': 'Цуцлах',
};
